dedupePeers: true
trustPolicy: no-downgrade

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - "@tb-dev/*"
  - "@tsukilabs/*"

overrides:
  nanoid@<3.3.18: ^3.3.18
  postcss@<=8.5.22: ^8.5.23
